"""Text cleanup filters for repository and transcript ingestion."""

from __future__ import annotations

import re


REMOVABLE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"(?im)^this transcript may contain mentions of chatgpt.*$"),
    re.compile(r"(?im)^subscribe to the channel\.?$"),
    re.compile(r"(?im)^like and subscribe\.?$"),
    re.compile(r"(?im)^generated by .*(chatgpt|claude|ai).*$"),
    re.compile(r"(?im)^autogenerated footer:.*$"),
)


def cleanup_text(text: str) -> str:
    """Return normalized text with common transcript and generated noise removed."""
    cleaned = text.replace("\r\n", "\n").replace("\r", "\n")

    for pattern in REMOVABLE_PATTERNS:
        cleaned = pattern.sub("", cleaned)

    cleaned = _collapse_repeated_boilerplate(cleaned)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    return cleaned.strip() + ("\n" if cleaned.strip() else "")


def _collapse_repeated_boilerplate(text: str) -> str:
    lines = text.split("\n")
    seen_counts: dict[str, int] = {}
    kept: list[str] = []

    for line in lines:
        key = line.strip().lower()
        if len(key) < 20:
            kept.append(line)
            continue

        seen_counts[key] = seen_counts.get(key, 0) + 1
        if seen_counts[key] <= 2:
            kept.append(line)

    return "\n".join(kept)

